// K2 config (PUBLIC). Fill these before deploy.
window.K2_CONFIG = {
  GAS_WEBAPP_URL: "PASTE_GOOGLE_APPS_SCRIPT_WEBAPP_URL_HERE",
  STRIPE_LINK_BASIC: "PASTE_STRIPE_LINK_BASIC",
  STRIPE_LINK_COMFORT: "PASTE_STRIPE_LINK_COMFORT",
  STRIPE_LINK_PRO: "PASTE_STRIPE_LINK_PRO",
  STRIPE_LINK_EXTRA_MATTRESS: "PASTE_STRIPE_LINK_EXTRA_MATTRESS",
  STRIPE_LINK_EXTRA_BAG: "PASTE_STRIPE_LINK_EXTRA_BAG",
  STRIPE_LINK_EXTRA_FASTKIT: "PASTE_STRIPE_LINK_EXTRA_FASTKIT"
};